"""Support matrix generator (``log-triage --support-matrix``).

The matrix is derived from the code (text layouts, structured dialects, document
envelopes, parser registry) so docs/log-triage/support-matrix.md cannot claim a format
that has no implementation; the test suite checks the checked-in file is fresh.
"""
from __future__ import annotations

from typing import List

from .parsers.structured import DIALECTS, ENVELOPES
from .parsers.text import LAYOUTS


def _md(s: str) -> str:
    return (s or "").replace("|", "\\|").replace("\n", " ")


def render() -> str:
    o: List[str] = []
    o.append("# /log-triage format support matrix\n")
    o.append("<!-- GENERATED by `python3 scripts/log-triage --support-matrix`; edit the source tables in log_triage/parsers instead. -->\n")
    o.append("A library name is not a format: every row below names the **layout, dialect or export shape** that is implemented, "
             "how it is detected, what is extracted, and its limits. Every row is exercised by a fixture in `tests/log-triage/fixtures/` "
             "(`tests/log-triage/test_formats.py`). Anything not listed is not claimed.\n")
    o.append("## Detection behaviour\n")
    o.append("* A bounded head sample (`detect_sample_bytes`, default 64 KiB / `detect_sample_lines` 256 lines, decompressed) is scored by every parser; "
             "the best score wins and is reported as `detection_confidence` per input. Below 0.3 the `--fallback-format` (default `text`) is used and a "
             "`low-detection-confidence` diagnostic is recorded.\n"
             "* `--input-format <parser>` or `--input-format text:<layout>` bypasses detection.\n"
             "* Text files pick up to three layouts when the sample mixes them (e.g. Monolog lines with PHP error_log lines); lines matching none of them fall back "
             "to generic timestamp/level headers, then to headerless records (`unknown-text-layout` diagnostic when the whole sample has no recognisable header).\n"
             "* Compression: gzip (magic `1f 8b`, multi-member, streamed, bounded by `max_decompressed_bytes` / `max_compression_ratio`). bzip2/xz/zstd/zip/7z/rar/lz4 are "
             "detected by magic and reported as unsupported with the decompression command to run. Binary EVTX (`ElfFile`), systemd journal (`LPKSHHRH`), ETL, PE/ELF, "
             "PDF, PNG, PCAP and SQLite files are detected and excluded with an actionable diagnostic; there is no text fallback for them.\n"
             "* Encodings: UTF-8 (BOM optional; invalid bytes replaced and counted), UTF-16 LE/BE (BOM or NUL-pattern heuristic; byte offsets approximate). Other legacy encodings decode as UTF-8 with replacement characters.\n")
    o.append("## Plain-text layouts (`text` parser)\n")
    o.append("| Layout id (`--input-format text:<id>`) | Ecosystem | Library / producer | Example line | Notes and limitations |")
    o.append("|---|---|---|---|---|")
    for l in LAYOUTS:
        o.append("| `%s` | %s | %s | `%s` | %s |" % (l.id, _md(l.ecosystem), _md(l.family), _md(l.example.split("\n")[0]).replace("`", "'"), _md(l.notes)))
    o.append("")
    o.append("Common to all text layouts: multiline continuation (stack traces, indented payloads) is folded into the event (bounded by `max_multiline_lines` / "
             "`max_record_bytes`); exception headlines, cause chains and frames are recognised for Java/Kotlin/Scala, .NET, Python, Node, Go (panics), Rust (panics, "
             "backtraces), Ruby, PHP, Elixir/Erlang, C/C++ (assertions, sanitizers, gdb-style frames), Swift/Objective-C (crash reports) and PowerShell error records "
             "(see `parsers/exceptions.py`). Time-only stamps (Logback/log4j2 default `HH:mm:ss.SSS`, Elixir default, Zerolog console, Serilog `[HH:mm:ss INF]`) yield no "
             "usable timestamp: the event is counted, kept, and excluded by `--since` unless `--keep-untimed`.\n")
    o.append("## Structured (JSON) dialects (`ndjson` / `json` parsers)\n")
    o.append("| Dialect id | Ecosystem | Library / producer | Signature keys | Fixture | Notes |")
    o.append("|---|---|---|---|---|---|")
    sigs = {
        "otlp": "`timeUnixNano`/`observedTimeUnixNano` + `body`/`severityText`/`severityNumber`", "serilog-compact": "`@t` + `@m`/`@mt`",
        "serilog-json": "`Timestamp` + `Level` + `RenderedMessage`/`MessageTemplate`", "log4j2-json": "`instant`{epochSecond} or `timeMillis` + `loggerName`",
        "logstash-logback": "`@timestamp` + `logger_name` + `level`", "python-json-logger": "`levelname` + `asctime`/`message`/`name`",
        "structlog-json": "`event` + `level` + `timestamp`", "loguru-serialized": "`record`{} + `text`", "pino": "integer `level` + `time` + `msg`",
        "bunyan": "integer `level` + `v` + `msg` + `hostname`", "winston-json": "string `level` + `message` (+ `timestamp`/`service`/`stack`)",
        "slog-json": "`time` + upper-case `level` + `msg`", "zap-json": "`level` + `msg` + `ts`/`caller`", "zerolog": "`level` + `time` + `message`",
        "tracing-json": "`fields`{} + `target` + `level`", "monolog-json": "`message` + `channel` + `level_name`",
        "ecs": "`@timestamp` + `log.level`/`ecs.version` (nested or dotted)", "journal-json": "`__REALTIME_TIMESTAMP` or `MESSAGE`+`PRIORITY`",
        "docker-json-file": "`log` + `stream` + `time`", "cri": "text: `<RFC3339> stdout|stderr P|F <content>`",
        "cloudwatch-event": "`message` + integer `timestamp` + `ingestionTime`/`logStreamName`/`eventId`/`id`",
        "cloudwatch-insights": "envelope `results[[{field,value}]]`", "azure-record": "`time` + `resourceId` + `category`/`operationName`",
        "azure-row": "envelope `tables[{columns,rows}]`", "gcp-logentry": "`logName`/`insertId` + `textPayload`/`jsonPayload`/`protoPayload`",
        "loki-logcli": "`labels` + `line` + `timestamp`", "loki-stream": "envelope `data.result[{stream,values}]`",
        "apple-ips": "header object (`bug_type`) + body with `faultingThread`/`threads`", "generic-json": "any object (common key names)",
    }
    for d in DIALECTS:
        o.append("| `%s` | %s | %s | %s | `%s` | %s |" % (d.id, _md(d.ecosystem), _md(d.library), sigs.get(d.id, ""), d.fixture, _md(d.notes)))
    o.append("")
    o.append("NDJSON is parsed line by line (`json.loads`, one record per line; non-JSON lines between records are parsed as text and reported with a "
             "`non-json-line` diagnostic). JSON documents (arrays, envelopes, pretty-printed or concatenated objects) are scanned incrementally by a boundary "
             "scanner so only one record is in memory at a time; items larger than `max_record_bytes` are skipped with an `oversized-record` diagnostic. "
             "Structured exception fields (`exception`, `stack_trace`, `err`, `thrown`, `error.stack_trace`, ...) are normalised whether they are strings, "
             "objects (type/message/stack/cause) or frame lists.\n")
    o.append("## Document envelopes and platform export shapes\n")
    o.append("| Envelope id | Detected by | Item path | Context captured | Dialect applied | Shape |")
    o.append("|---|---|---|---|---|---|")
    detect_text = {
        "otlp": "`\"resourceLogs\"` in head", "cloudwatch-subscription": "`\"logEvents\"` + `\"messageType\"`",
        "cloudwatch-events": "`\"events\"` + `nextForwardToken`/`ingestionTime`/`searchedLogStreams`/`logStreamName`",
        "cloudwatch-insights": "`\"results\"` + `\"field\"` + `\"value\"`", "azure-tables": "`\"tables\"` + `\"columns\"`",
        "loki-streams": "`\"resultType\"` + `\"streams\"`/`\"values\"`", "elasticsearch-hits": "`\"hits\"` + `\"_source\"`",
        "records": "root object; the array is its `records` member", "events": "root object; the array is its `events` member",
        "entries": "root object; the array is its `entries` member", "logs": "root object; the array is its `logs` member",
        "items": "root object; the array is its `items` member", "messages": "root object; the array is its `messages` member",
        "Records": "root object; the array is its `Records` member", "data-array": "root object `{\"data\": [...]}`",
    }
    for e in ENVELOPES:
        o.append("| `%s` | %s | `%s` | %s | %s | %s |" % (e.id, detect_text.get(e.id, ""), "/".join(str(p) for p in e.item_paths[0]) or "(root)",
                                                     ", ".join("`" + "/".join(str(p) for p in c) + "`" for c in e.capture_paths) or "—",
                                                     ("`%s`" % e.dialect) if e.dialect else "per-record detection", _md(e.label)))
    o.append("")
    o.append("Platform adapters cover **exported / API-response** shapes only; there are no live platform connections:\n")
    o.append("* **AWS CloudWatch Logs**: `GetLogEvents` / `FilterLogEvents` responses (`events[]`), subscription-filter `DATA_MESSAGE` documents (`logEvents[]`, "
             "`logGroup`/`logStream`/`owner` captured), and Logs Insights `GetQueryResults` (`results[][{field,value}]`). The inner `message` is parsed as text or JSON "
             "(multi-line messages are re-assembled across records).\n"
             "* **Azure Monitor / Application Insights**: Log Analytics and App Insights query API responses (`tables[].columns/rows`, column names such as `TimeGenerated`, "
             "`SeverityLevel`, `Message`, `OuterMessage`, `ExceptionType`, `AppRoleName`, `OperationId`, `ResultCode`) and diagnostic-settings exports "
             "(`records[]` or NDJSON with `time`/`resourceId`/`category`/`operationName`/`properties`). The legacy continuous-export blob format is not supported.\n"
             "* **Google Cloud Logging**: `LogEntry` objects as an array (`gcloud logging read --format=json`) or NDJSON (Cloud Storage export sinks): `textPayload`, "
             "`jsonPayload` (incl. Error Reporting `ReportedErrorEvent` messages), `protoPayload`, `resource.labels`, `httpRequest`, `trace`/`spanId`, `sourceLocation`.\n"
             "* **Grafana Loki**: `query_range` streams results (`data.result[].stream` labels + `values[][ts, line]`) and `logcli --output=jsonl` lines.\n")
    o.append("## Other line formats\n")
    o.append("| Parser | Detected by | Extracted | Limitations |")
    o.append("|---|---|---|---|")
    o.append("| `syslog` | RFC 5424 (`<PRI>1 ...`) or RFC 3164 (`Mmm dd hh:mm:ss host tag[pid]:`; rsyslog RFC 3339 and Apple `log show --style syslog` variants) on >= 50% of sampled lines | PRI -> facility/severity, host, tag (service), pid, MSGID, STRUCTURED-DATA params, message (exceptions in message tails) | RFC 3164 has no year (inferred from `--now`, `year_inferred` flag) and no zone (`--assume-tz`); octet-counted framing is not supported |")
    o.append("| `access-log` | Apache/Nginx Common or Combined lines, Nginx error lines, Apache 2.2/2.4 error lines on >= 50% of sampled lines | method, path (query dropped), status, bytes, client ip, user agent; nginx `client/server/request/upstream/host`; Apache module + `AHxxxxx` codes | Custom `LogFormat` strings are not parsed (fall back to text) |")
    o.append("| `iis-w3c` | `#Fields:` directive with `#Software:`/`#Version:`/`#Date:` | fields per the declared order (re-declarations honoured mid-file); `date`+`time` combined as UTC; `sc-status`, `cs-method`, `cs-uri-stem`, `time-taken`, ... | NCSA/IIS-native formats are not W3C and fall back to text |")
    o.append("| `csv` / `tsv` | >= 70% of logical rows share a column count >= 3 (RFC 4180 quoting, embedded newlines) and the first row looks like a header | header-based column mapping (timestamp/level/message/logger/service/host/exception/request id/status/method/path), other columns as attributes; headerless files map columns heuristically | delimiter is `,`/`;`/`|` (csv) or TAB (tsv); a `date` column plus a `time` column are combined |")
    o.append("| `logfmt` | >= 60% of lines are `key=value` sequences (quoted values with escapes) | same key mapping as generic JSON (`time`/`level`/`msg`/`err`, ...) | non-logfmt lines are parsed as text with a `logfmt-malformed-line` diagnostic |")
    o.append("| `cri` | `<RFC3339> stdout|stderr P|F <content>` on >= 60% of lines | timestamp, stream; partial (`P`) records reassembled until `F`; inner content parsed as text or JSON | an unterminated `P` sequence is emitted with `cri.unterminated` and a diagnostic |")
    o.append("| `xml` / `winevt-xml` | document or fragment starting with `<` (Windows Event Log namespace or `<Events>`+`<System>` for `winevt-xml`) | Windows Event Log XML (System/EventData/RenderingInfo), log4j/NLog `log4j:event`, log4net `log4net:event`, java.util.logging `<record>`, and generic repeated child elements | expat streaming; DOCTYPE with entities and any external entity reference are rejected (`xml-entity-rejected`); records with > 2048 elements are truncated |")
    o.append("| `apple-crash` | `Incident Identifier:`/`Exception Type:`/`Thread 0 Crashed` markers | one event per report: process, identifier, version, OS, exception type/codes, crashed-thread frames (symbolicated file:line when present) | `.ips` JSON reports are handled by the `apple-ips` dialect; unsymbolicated frames keep the image name only |")
    o.append("")
    o.append("## Not supported (detected, reported, never silently parsed)\n")
    o.append("* Binary EVTX, ETL, systemd journal files, PCAP, SQLite, executables: excluded with a conversion hint (`wevtutil qe /f:xml`, `tracerpt`, `journalctl -o json`).\n"
             "* bzip2 / xz / zstd / zip / 7z / rar / lz4 archives: excluded with the decompression command to run first.\n"
             "* Live platform connections (CloudWatch/Azure/GCP/Loki APIs): out of scope; export first.\n"
             "* Custom text layouts that match none of the layouts above are parsed by the generic timestamp/level fallback or as headerless records; the report says so.\n")
    return "\n".join(o) + "\n"
